structinit = {
    treeDemo_8: {
        "id": 3,
        "pId": null,
        "name": "父节点 3",
        "open": true,
        "children": [{
                "id": 31,
                "pId": 3,
                "name": "叶子节点 3-1",
                "level": 1,
                "tId": "treeDemo_10",
                "parentTId": "treeDemo_9",
                "open": false,
                "isParent": false,
                "zAsync": true,
                "isFirstNode": true,
                "isLastNode": false,
                "isAjaxing": false,
                "checked": false,
                "checkedOld": false,
                "nocheck": false,
                "chkDisabled": false,
                "halfCheck": false,
                "check_Child_State": -1,
                "check_Focus": false,
                "isHover": false,
                "editNameFlag": false
            },
            {
                "id": 32,
                "pId": 3,
                "name": "叶子节点 3-2",
                "level": 1,
                "tId": "treeDemo_11",
                "parentTId": "treeDemo_9",
                "open": false,
                "isParent": false,
                "zAsync": true,
                "isFirstNode": false,
                "isLastNode": false,
                "isAjaxing": false,
                "checked": false,
                "checkedOld": false,
                "nocheck": false,
                "chkDisabled": false,
                "halfCheck": false,
                "check_Child_State": -1,
                "check_Focus": false,
                "isHover": false,
                "editNameFlag": false
            },
            {
                "id": 33,
                "pId": 3,
                "name": "叶子节点 3-3",
                "level": 1,
                "tId": "treeDemo_12",
                "parentTId": "treeDemo_9",
                "open": false,
                "isParent": false,
                "zAsync": true,
                "isFirstNode": false,
                "isLastNode": true,
                "isAjaxing": false,
                "checked": false,
                "checkedOld": false,
                "nocheck": false,
                "chkDisabled": false,
                "halfCheck": false,
                "check_Child_State": -1,
                "check_Focus": false,
                "isHover": false,
                "editNameFlag": false
            }
        ],
        "level": 0,
        "tId": "treeDemo_9",
        "parentTId": null,
        "isParent": true,
        "zAsync": true,
        "isFirstNode": false,
        "isLastNode": true,
        "isAjaxing": false,
        "checked": false,
        "checkedOld": false,
        "nocheck": false,
        "chkDisabled": false,
        "halfCheck": false,
        "check_Child_State": 0,
        "check_Focus": false,
        "isHover": false,
        "editNameFlag": false
    }
}